implement bash strict mode for through pub modules

diff --git a/pipe/parQuantumLine/parQuantumLine_pub_group_and_package.yaml b/pipe/parQuantumLine/parQuantumLine_pub_group_and_package.yaml
--- a/pipe/parQuantumLine/parQuantumLine_pub_group_and_package.yaml
+++ b/pipe/parQuantumLine/parQuantumLine_pub_group_and_package.yaml
@@ -4,46 +4,52 @@ pipeline:
 transform:
   image_pull_secrets: [battelleecology-quay-read-all-pull-secret]
   image: quay.io/battelleecology/neon-is-pub-grp-pack:fe1512ea
-  cmd: ["/bin/bash"]
-  stdin:
-  - "#!/bin/bash"
-  - '# Refresh interim directories with each datum (otherwise they persist and cause probs)'
-  - rm -rf $OUT_PATH_GROUPER
-  - rm -rf $OUT_PATH_TRANSFORMER
-  - rm -rf $OUT_PATH_PACKAGER
-  - mkdir $OUT_PATH_GROUPER
-  - mkdir $OUT_PATH_TRANSFORMER
-  - mkdir $OUT_PATH_PACKAGER
-  - '# Set some environment variables for the first module'
-  - export OUT_PATH=$OUT_PATH_GROUPER
-  - '# Run first module - pub_grouper (using environment variables below as input parameters)'
-  - python3 -m pub_grouper.pub_grouper_main
-  - '# Set some environment variables for the second module'
-  - export DATA_PATH=$OUT_PATH_GROUPER
-  - export OUT_PATH=$OUT_PATH_TRANSFORMER
-  - export YEAR_INDEX=$YEAR_INDEX_TRANSFORMER
-  - export DATA_TYPE_INDEX=$DATA_TYPE_INDEX_TRANSFORMER
-  - '# Run second module - pub_transformer (using environment variables below as input parameters)'
-  - python3 -m pub_workbook_loader.pub_workbook_loader_main
-  - python3 -m pub_transformer.pub_transformer_main
-  - '# Set some environment variables for the third module'
-  - export OUT_PATH=$OUT_PATH_PACKAGER
-  - '# Packager needs to be run at monthly glob. Get those paths.'
-  - product_month_paths="${OUT_PATH_TRANSFORMER}/*/*/*"
-  - for path in $product_month_paths; do
-  - '  echo "Processing product-month path $path"'
-  - '  export DATA_PATH=$path' 
-  - '  # Run third module - pub_packager (using environment variables below as input parameters)'
-  - '  python3 -m pub_packager.pub_packager_main'
-  - done
-  - '# Clean up after 2nd module'
-  - rm -rf $OUT_PATH_TRANSFORMER
-  - '# Set some environment variables for the fourth module and do some cleanup'
-  - export OUT_PATH=$OUT_PATH_PUBFILES
-  - export IN_PATH=$OUT_PATH_PACKAGER
-  - export LOCATION_PATH=$OUT_PATH_GROUPER
-  - '# Run fourth module - pub_files (using environment variables below as input parameters)'
-  - python3 -m pub_files.main
+  cmd:
+  - sh
+  - "-c"
+  - |-
+    /bin/bash <<'EOF'
+    # Use bash-scrict mode. See http://redsymbol.net/articles/unofficial-bash-strict-mode/
+    set -euo pipefail
+    IFS=$'\n\t'
+    # Refresh interim directories with each datum (otherwise they persist and cause probs)
+    rm -rf $OUT_PATH_GROUPER
+    rm -rf $OUT_PATH_TRANSFORMER
+    rm -rf $OUT_PATH_PACKAGER
+    mkdir $OUT_PATH_GROUPER
+    mkdir $OUT_PATH_TRANSFORMER
+    mkdir $OUT_PATH_PACKAGER
+    # Set some environment variables for the first module
+    export OUT_PATH=$OUT_PATH_GROUPER
+    # Run first module - pub_grouper (using environment variables below as input parameters)
+    python3 -m pub_grouper.pub_grouper_main
+    # Set some environment variables for the second module
+    export DATA_PATH=$OUT_PATH_GROUPER
+    export OUT_PATH=$OUT_PATH_TRANSFORMER
+    export YEAR_INDEX=$YEAR_INDEX_TRANSFORMER
+    export DATA_TYPE_INDEX=$DATA_TYPE_INDEX_TRANSFORMER
+    # Run second module - pub_transformer (using environment variables below as input parameters)
+    python3 -m pub_workbook_loader.pub_workbook_loader_main
+    python3 -m pub_transformer.pub_transformer_main
+    # Set some environment variables for the third module
+    export OUT_PATH=$OUT_PATH_PACKAGER
+    # Packager needs to be run at monthly glob. Get those paths.
+    product_month_paths="${OUT_PATH_TRANSFORMER}/*/*/*"
+    for path in $product_month_paths; do
+      echo "Processing product-month path $path"
+      export DATA_PATH=$path
+      # Run third module - pub_packager (using environment variables below as input parameters)
+      python3 -m pub_packager.pub_packager_main
+    done
+    # Clean up after 2nd module
+    rm -rf $OUT_PATH_TRANSFORMER
+    # Set some environment variables for the fourth module and do some cleanup'
+    export OUT_PATH=$OUT_PATH_PUBFILES
+    export IN_PATH=$OUT_PATH_PACKAGER
+    export LOCATION_PATH=$OUT_PATH_GROUPER
+    # Run fourth module - pub_files (using environment variables below as input parameters)
+    python3 -m pub_files.main
+    EOF
   env:
     # Environment variables for 1st module: pub_grouper.
     LOG_LEVEL: INFO
