export to bucket under folder for dp-shortname

diff --git a/pipe/groundwaterPhysical/groundwaterPhysical_level1_group_consolidate_srf.yaml b/pipe/groundwaterPhysical/groundwaterPhysical_level1_group_consolidate_srf.yaml
--- a/pipe/groundwaterPhysical/groundwaterPhysical_level1_group_consolidate_srf.yaml
+++ b/pipe/groundwaterPhysical/groundwaterPhysical_level1_group_consolidate_srf.yaml
@@ -61,7 +61,7 @@ transform:
     out_parquet_glob="${OUT_PATH}/**/*.parquet"
     # Example: /2024/01/18/par-quantum-line_UKFS001000/data/par-quantum-line_UKFS001000_2024-01-18_PARQL_1min_001.parquet
     echo "Linking output files to ${linkdir}"
-    #set -x # Echo commands to output for debugging
+    # set -x # Echo commands to output for debugging
     fname=""
     for f in $out_parquet_glob; do
       if [[ -f "$f" ]]; then
@@ -72,16 +72,30 @@ transform:
         fday="${BASH_REMATCH[3]}"
         fgroup="${BASH_REMATCH[4]}"
         fname="${BASH_REMATCH[5]}"
-        # Now get the timing index from the file name
-        [[ "$fname" =~ ^${GROUP_PREFIX}_[A-Z]+[0-9]+_${fyear}-${fmonth}-${fday}_[A-Za-z0-9]+_([A-Za-z0-9]+)_([A-Za-z0-9]+).parquet ]]
-        avg_int="${BASH_REMATCH[1]}"
+        
+        # Now get the data product and timing index from the file name
+        [[ "$fname" =~ ^${GROUP_PREFIX}_[A-Z]+[0-9]+_${fyear}-${fmonth}-${fday}_([A-Za-z0-9]+)_[A-Za-z0-9]+_[A-Za-z0-9]+_([A-Za-z0-9]+).parquet ]]
+        table_prefix="${BASH_REMATCH[1]}"
+        unset dp_shortname
+        if [[ $table_prefix = "EOG" ]]; then
+          dp_shortname="elev-groundwater"
+        elif [[ $table_prefix = "TGW" ]]; then
+          dp_shortname="temp-groundwater"
+        elif [[ $table_prefix = "SCGW" ]]; then
+          dp_shortname="cond-groundwater"
+        else
+          echo "FATAL: Cannot determine data product shortname from $fname"
+          exit 1
+        fi
+        avg_int="${BASH_REMATCH[2]}"
+        
         #Form the output path and link
-        outdir="${linkdir}/v2/${GROUP_PREFIX}/${avg_int}/group=${fgroup}/ms=${fyear}-${fmonth}"
+        outdir="${linkdir}/v2/${dp_shortname}/${avg_int}/group=${fgroup}/ms=${fyear}-${fmonth}"
         mkdir -p "${outdir}"
         ln -s "${f}" "${outdir}/${fname}"
       fi
     done
-    #set +x
+    # set +x
     if [[ "${fname}" ]]; then
       echo "Syncing files to bucket"
       rclone \
diff --git a/pipe/surfacewaterPhysical/surfacewaterPhysical_level1_group_consolidate_srf.yaml b/pipe/surfacewaterPhysical/surfacewaterPhysical_level1_group_consolidate_srf.yaml
--- a/pipe/surfacewaterPhysical/surfacewaterPhysical_level1_group_consolidate_srf.yaml
+++ b/pipe/surfacewaterPhysical/surfacewaterPhysical_level1_group_consolidate_srf.yaml
@@ -52,49 +52,63 @@ transform:
       "DirData=data|sci_stats|uncertainty_data|stats|quality_metrics" \
       PathPubWb=$PUB_WORKBOOKS \
       "DirSubCopy=science_review_flags|group|location"
-    #
-    #
-    # # Export Level 1 data to bucket 
-    # export OUT_PATH=/pfs/out
-    # linkdir=$(mktemp -d)
-    # shopt -s globstar
-    # out_parquet_glob="${OUT_PATH}/**/*.parquet"
-    # # Example: /2024/01/18/surfacewater-physical_ARIK101100/data/surfacewater-physical_ARIK101100_2022-04-04_EOS_30_min_030.parquet
-    # echo "Linking output files to ${linkdir}"
-    # #set -x # Echo commands to output for debugging
-    # fname=""
-    # for f in $out_parquet_glob; do
-    #   if [[ -f "$f" ]]; then
-    #     # Parse the path
-    #     [[ "$f" =~ ^$OUT_PATH/([0-9]+)/([0-9]+)/([0-9]+)/(${GROUP_PREFIX}_[A-Za-z0-9]+)/data/(.*)$ ]]
-    #     fyear="${BASH_REMATCH[1]}"
-    #     fmonth="${BASH_REMATCH[2]}"
-    #     fday="${BASH_REMATCH[3]}"
-    #     fgroup="${BASH_REMATCH[4]}"
-    #     fname="${BASH_REMATCH[5]}"
-    #     # Now get the timing index from the file name
-    #     [[ "$fname" =~ ^${GROUP_PREFIX}_[A-Z]+[0-9]+_${fyear}-${fmonth}-${fday}_[A-Za-z0-9]+_([A-Za-z0-9]+)_([A-Za-z0-9]+).parquet ]]
-    #     avg_int="${BASH_REMATCH[1]}"
-    #     #Form the output path and link
-    #     outdir="${linkdir}/v2/${GROUP_PREFIX}/${avg_int}/group=${fgroup}/ms=${fyear}-${fmonth}"
-    #     mkdir -p "${outdir}"
-    #     ln -s "${f}" "${outdir}/${fname}"
-    #   fi
-    # done
-    # #set +x
-    # if [[ "${fname}" ]]; then
-    #   echo "Syncing files to bucket"
-    #   rclone \
-    #     --no-check-dest \
-    #     --copy-links \
-    #     --gcs-bucket-policy-only \
-    #     --gcs-no-check-bucket \
-    #     copy \
-    #     "${linkdir}" \
-    #     ":gcs://${BUCKET_NAME}"
-    #   echo "Removing temporary files"
-    #   rm -rf $linkdir
-    # fi
+
+
+    # Export Level 1 data to bucket
+    export OUT_PATH=/pfs/out
+    linkdir=$(mktemp -d)
+    shopt -s globstar
+    out_parquet_glob="${OUT_PATH}/**/*.parquet"
+    # Example: /2024/01/18/surfacewater-physical_ARIK101100/data/surfacewater-physical_ARIK101100_2022-04-04_EOS_30_min_030.parquet
+    echo "Linking output files to ${linkdir}"
+    #set -x # Echo commands to output for debugging
+    fname=""
+    for f in $out_parquet_glob; do
+      if [[ -f "$f" ]]; then
+        # Parse the path
+        [[ "$f" =~ ^$OUT_PATH/([0-9]+)/([0-9]+)/([0-9]+)/(${GROUP_PREFIX}_[A-Za-z0-9]+)/data/(.*)$ ]]
+        fyear="${BASH_REMATCH[1]}"
+        fmonth="${BASH_REMATCH[2]}"
+        fday="${BASH_REMATCH[3]}"
+        fgroup="${BASH_REMATCH[4]}"
+        fname="${BASH_REMATCH[5]}"
+        
+        # Now get the data product and timing index from the file name
+        [[ "$fname" =~ ^${GROUP_PREFIX}_[A-Z]+[0-9]+_${fyear}-${fmonth}-${fday}_([A-Za-z0-9]+)_[A-Za-z0-9]+_[A-Za-z0-9]+_([A-Za-z0-9]+).parquet ]]
+        table_prefix="${BASH_REMATCH[1]}"
+        unset dp_shortname
+        if [[ $table_prefix = "EOS" ]]; then
+          dp_shortname="elev-surfacewater"
+        elif [[ $table_prefix = "TOSW" ]]; then
+          dp_shortname="temp-digital-surfacewater"
+        elif [[ $table_prefix = "SCSW" ]]; then
+          dp_shortname="conductivity-surface-water"
+        else
+          echo "FATAL: Cannot determine data product shortname from $fname"
+          exit 1
+        fi
+        avg_int="${BASH_REMATCH[2]}"
+        
+        #Form the output path and link
+        outdir="${linkdir}/v2/${dp_shortname}/${avg_int}/group=${fgroup}/ms=${fyear}-${fmonth}"
+        mkdir -p "${outdir}"
+        ln -s "${f}" "${outdir}/${fname}"
+      fi
+    done
+    #set +x
+    if [[ "${fname}" ]]; then
+      echo "Syncing files to bucket"
+      rclone \
+        --no-check-dest \
+        --copy-links \
+        --gcs-bucket-policy-only \
+        --gcs-no-check-bucket \
+        copy \
+        "${linkdir}" \
+        ":gcs://${BUCKET_NAME}"
+      echo "Removing temporary files"
+      rm -rf $linkdir
+    fi
     EOF
   env:
     # Environment variables for 1st filter-joiner. Need to join by day again here because an outer join was used on 
